{{- range .Values.clusters }}
---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: '{{ .name }}'
  namespace: '{{ .name }}'
  labels:
    cloud: 'vSphere'
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: 'default'
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  baseDomain: '{{ .baseDomain }}'
  clusterName: '{{ .name }}'
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  installed: false
  platform:
    vsphere:
      cluster: '{{ .cluster }}'
      certificatesSecretRef:
        name: '{{ .name }}-vsphere-certs'
      credentialsSecretRef:
        name: '{{ .name }}-vsphere-creds'
      vCenter: '{{ .platform.vsphere.vCenter }}'
      datacenter: '{{ .platform.vsphere.datacenter }}'
      defaultDatastore: '{{ .platform.vsphere.defaultDatastore }}'
      network: '{{ .platform.vsphere.network }}'
  provisioning:
    installConfigSecretRef:
      name: '{{ .name }}-install-config'
    sshPrivateKeySecretRef:
      name: '{{ .name }}-ssh-private-key'
    imageSetRef:
      name: '{{ .imageSetRef }}'
  pullSecretRef:
    name: '{{ .name }}-pull-secret'
{{- end }}

