{{- range .Values.clusters }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
  namespace: {{ .name }}
spec:
  encryptedData:
    install-config.yaml: {{ .secrets.installConfig }}
  template:
    metadata:
      name: {{ .name }}
      namespace: {{ .name }}
    type: Opaque
{{- end }}

