{{- range .Values.clusters }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
  namespace: {{ .name }}
spec:
  encryptedData:
    .dockerconfigjson: encrypted-pull-secret
  template:
    metadata:
      name: {{ .name }}
      namespace: {{ .name }}
    type: kubernetes.io/dockerconfigjson
{{- end }}
